"""Configuration for postoperative recovery regression."""

from pathlib import Path


EXP_DIR = Path(__file__).resolve().parent
REPO_ROOT = EXP_DIR.parents[1]
DATA_ROOT = Path("/root/shared/HealthMirrorDataset")
LAB_METADATA_CSV = REPO_ROOT / "merged_lab_tests.csv"
PATIENT_INFO_GLOB = str(REPO_ROOT / "merged_patient_info_*.csv")
WEIGHTS_DIR = REPO_ROOT / "study/exp2_face_pretrained/pretrained_weights"
OUTPUT_DIR = EXP_DIR / "outputs"
CACHE_DIR = EXP_DIR / "cache"
LOG_DIR = EXP_DIR / "logs"

TIMEZONE = "Asia/Shanghai"
MAX_TIME_SOURCE_DELTA_SECONDS = 300.0
SEED = 20260806
SEEDS = (20260806, 20260807, 20260808, 20260809)
SPLIT_FRACTIONS = (0.60, 0.20, 0.20)
SPLIT_CANDIDATES = 512
SPLIT_SCORE_BINS = 10

ARCHITECTURE = "efficientnet_b0"
PRETRAINED_WEIGHT_FILE = "efficientnet_b0_rwightman-7f5810bc.pth"
HEAD_HIDDEN_FEATURES = 32
IMAGE_SIZE = 224
SOURCE_IMAGE_SIZE = 128
IMAGENET_MEAN = (0.485, 0.456, 0.406)
IMAGENET_STD = (0.229, 0.224, 0.225)

FRAMES_PER_VIDEO = 20
FRAME_QUANTILES = tuple(0.05 + 0.90 * index / 19 for index in range(20))
MIN_SOURCE_FRAME_GAP = 2
TRAIN_VIEWS = ("original", "hflip", "center_crop")
CROP_SCALE = 0.90

TRAIN_SOURCE_BATCH_SIZE = 48
EVAL_BATCH_SIZE = 384
TRAIN_NUM_WORKERS = 4
EVAL_NUM_WORKERS = 2
PREFETCH_FACTOR = 4
MAX_OPEN_FILES_PER_WORKER = 64
DECODE_CACHE_FRAMES = 16

HEAD_LEARNING_RATE = 1e-3
FINETUNE_HEAD_LEARNING_RATE = 1e-4
FINETUNE_BACKBONE_LEARNING_RATE = 1e-5
WEIGHT_DECAY = 1e-4
HEAD_MAX_EPOCHS = 25
FINETUNE_MAX_EPOCHS = 40
HEAD_PATIENCE = 8
FINETUNE_PATIENCE = 10
MIN_LEARNING_RATE = 1e-6
GRAD_CLIP_NORM = 1.0
SMOOTH_L1_BETA = 0.10
TORCH_COMPILE_ENABLED = True
TORCH_COMPILE_MODE = "reduce-overhead"
